saveprefix: Transfer_model2
Regressionyaml: simplemodel

# datasetpath: Aug29
train_datasetpath: /home/ddemler/HNLclassifier/saved_files/extracted_data/TEST10_train1_multitrain_Sep8
val_datasetpath: /home/ddemler/HNLclassifier/saved_files/extracted_data/TEST10_val1_multitrain_Sep8
test_datasetpath: /home/ddemler/HNLclassifier/saved_files/extracted_data/TEST10_train2_multitrain_Sep8

dropout: 0.5 # dropout probability, set to 0 if you dont want dropout

transfer_activation: F.relu
transfer_hidden_layers: 
- 128
- 128

optimizer: torch.optim.AdamW
optimizer_params:
  weight_decay: 0.0001
  lr: 0.0002

scheduler_patience: 3
scheduler_factor: 0.5
model_patience: 10
unfreeze_epoch: 5
num_epochs: 100